name: windows-cmake-cl-build

on: [push, pull_request]
env:
  VulkanSDKVersion: 1.2.162.1

jobs:
 build-windows-cl:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v2
     with:
      lfs: 'true'
   - uses: ashutoshvarma/setup-ninja@v1.1
     with:
      version: 1.10.2
   - name: Set env
     id: env
     run: echo "::set-output name=VULKAN_SDK::C:\VulkanSDK\${{env.VulkanSDKVersion}}"
   - name: Cache
     id: cache
     uses: actions/cache@v1.1.2
     with:
      path: ${{steps.env.outputs.VULKAN_SDK}}
      key: VulkanSdk${{env.VulkanSDKVersion}}WindowsExtracted2
   - name: Download & Install Vulkan SDK
     if: steps.cache.outputs.cache-hit != 'true'
     run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/windows/VulkanSDK-${{env.VulkanSDKVersion}}-Installer.exe?u= -OutFile ../vulkan-sdk-${{env.VulkanSDKVersion}}.exe
        $installer = Start-Process -FilePath ../vulkan-sdk-${{env.VulkanSDKVersion}}.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
   - name: Configure and Build
     shell: cmd
     run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -S . -G Ninja -B build -DBUILD_TEST=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER:FILEPATH=cl.exe -D CMAKE_CXX_COMPILER:FILEPATH=cl.exe
        cmake --build build --target all
     env:
        VULKAN_SDK: ${{steps.env.outputs.VULKAN_SDK}}