name: macos-cmake-build

on: [push, pull_request]
env:
  VulkanSDKVersion: 1.2.162.1
  
jobs:
 build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
       lfs: 'true'
    - uses: ashutoshvarma/setup-ninja@v1.1
      with:
       version: 1.10.2
    - name: Set env
      id: env
      run: |
        brew install SDL2
        brew install googletest
        VULKAN_SDK=$GITHUB_WORKSPACE/../vulkansdk-macos-${{env.VulkanSDKVersion}}/macOS
        echo ::set-output name=VULKAN_SDK::$VULKAN_SDK
        echo "VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d" >> $GITHUB_ENV
        echo "VK_ICD_FILENAMES=$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json" >> $GITHUB_ENV
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{steps.env.outputs.VULKAN_SDK}}
        key: VulkanSdk${{env.VulkanSDKVersion}}ExtractedMacos
    - name: Download & Extract Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget --no-cookies -O ../vulkansdk-macos-${{env.VulkanSDKVersion}}.dmg https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/mac/vulkansdk-macos-${{env.VulkanSDKVersion}}.dmg?u=
        hdiutil attach ../vulkansdk-macos-${{env.VulkanSDKVersion}}.dmg
        cp -r /Volumes/vulkansdk-macos-${{env.VulkanSDKVersion}} $GITHUB_WORKSPACE/..
        hdiutil detach /Volumes/vulkansdk-macos-${{env.VulkanSDKVersion}}
    - name: Configure and Build
      run: |
        cmake -S . -G Ninja -B build -DBUILD_TEST=OFF -DBUILD_SPIRV_SHADER=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER:FILEPATH=clang -D CMAKE_CXX_COMPILER:FILEPATH=clang++
        cmake --build build --target all
      env:
        VULKAN_SDK: ${{steps.env.outputs.VULKAN_SDK}}