name: macos-build-shipping

on: [push, pull_request]

jobs:
  build-macos-shipping:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: "true"
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install mako
      - name: Set env
        id: env
        run: |
          xmake g -c
          xmake l setup.lua
      - name: Shipping
        if: success() || failure()
        run: |
          xmake f -m release -y --build_tests=n --build_editors=n -c --module_as_objects=y --use_tracy=disable --policies=build.ccache:n
          xmake -y -v
      - name: UploadGeneratedFiles
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: artifact-files
          path: build/.gens
      - name: UploadShipping
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/macosx
