name: windows-xmake-build

on: [push, pull_request]
env:
  VulkanSDKVersion: 1.2.162.1

jobs:
 build-windows:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v2
     with:
      lfs: 'true'
   - name: Set env
     id: env
     run: echo "::set-output name=VULKAN_SDK::C:\VulkanSDK\${{env.VulkanSDKVersion}}"
   - name: Cache
     id: cache
     uses: actions/cache@v1.1.2
     with:
      path: ${{steps.env.outputs.VULKAN_SDK}}
      key: VulkanSdk${{env.VulkanSDKVersion}}WindowsExtracted2
   - name: Download & Install Vulkan SDK
     if: steps.cache.outputs.cache-hit != 'true'
     run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/windows/VulkanSDK-${{env.VulkanSDKVersion}}-Installer.exe?u= -OutFile ../vulkan-sdk-${{env.VulkanSDKVersion}}.exe
        $installer = Start-Process -FilePath ../vulkan-sdk-${{env.VulkanSDKVersion}}.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
   - name: Debug
     shell: cmd
     run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        xmake f -m debug -cc=clang-cl -cxx=clang-cl -c
        xmake
     env:
        VULKAN_SDK: ${{steps.env.outputs.VULKAN_SDK}}
   - name: Release
     shell: cmd
     run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        xmake f -m release -cc=clang-cl -cxx=clang-cl -c
        xmake
     env:
        VULKAN_SDK: ${{steps.env.outputs.VULKAN_SDK}}